name: Download Blogger Sitemap Daily

on:
  schedule:
    - cron: '0 0 * * *' # Ogni giorno a mezzanotte
  workflow_dispatch:

jobs:
  download-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Importante per evitare errori di autenticazione

      - name: Download sitemap.xml
        run: |
          curl -L "https://thecollectorlab.blogspot.com/sitemap.xml" -o sitemap.xml

      - name: Commit e Push modifiche
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add sitemap.xml
          git commit -m "Aggiornamento automatico sitemap $(date +'%Y-%m-%d')" || exit 0
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
